### PR TITLE
TypeObject.h and IDL-to-C++11 code generation support for forward-declared types

### LINKED ISSUE #5076: No github action build with c++23 enabled
C++23 does make several changes to the STL, there should be a gcc/clang build with C++23 enabled to check if everything works

### LINKED ISSUE #5091: OpenDDS core doesn't compile with clang20 and C++23 enabled
See https://github.com/OpenDDS/OpenDDS/pull/5088, looks the core doesn't compile yet with clang20 and C++23

```
clang++-20 -std=c++23 -g   -O0 -DACE_HAS_CUSTOM_EXPORT_MACROS=0  -I/home/runner/work/OpenDDS/OpenDDS/ACE_TAO/ACE -DACE_NO_INLINE -I/home/runner/work/OpenDDS/OpenDDS/ACE_TAO/ACE -I../common  -c -o .obj/main.o /home/runner/work/OpenDDS/OpenDDS/OpenDDS/performance-tests/DCPS/TCPProfilingTest/raw_tcp/subscriber/main.cpp
In file included from /home/runner/work/OpenDDS/OpenDDS/OpenDDS/dds/DCPS/XTypes/TypeObject.cpp:7:
In file included from /home/runner/work/OpenDDS/OpenDDS/OpenDDS/dds/DCPS/XTypes/TypeObject.h:9:
In file included from /home/runner/work/OpenDDS/OpenDDS/OpenDDS/dds/DCPS/XTypes/External.h:9:
In file included from /home/runner/work/OpenDDS/OpenDDS/OpenDDS/dds/DCPS/unique_ptr.h:4:
In file included from /home/runner/work/OpenDDS/OpenDDS/OpenDDS/dds/DCPS/Definitions.h:15:
In file included from /home/runner/work/OpenDDS/OpenDDS/ACE_TAO/ACE/ace/Message_Block.h:25:
In file included from /home/runner/work/OpenDDS/OpenDDS/ACE_TAO/ACE/ace/Time_Value.h:25:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/chrono:49:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/shared_ptr.h:53:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/shared_ptr_base.h:59:
Error: /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/unique_ptr.h:91:16: error: invalid application of 'sizeof' to an incomplete type 'OpenDDS::XTypes::TypeIdentifier'
   91 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/unique_ptr.h:398:4: note: in instantiation of member function 'std::default_delete<OpenDDS::XTypes::TypeIdentifier>::operator()' requested here
  398 |           get_deleter()(std::move(__ptr));
      |           ^
/home/runner/work/OpenDDS/OpenDDS/OpenDDS/dds/DCPS/XTypes/External.h:26:7: note: in instantiation of member function 'std::unique_ptr<OpenDDS::XTypes::TypeIdentifier>::~unique_ptr' requested here
   26 | class External {
      |       ^
/home/runner/work/OpenDDS/OpenDDS/OpenDDS/dds/DCPS/XTypes/TypeObject.h:409:5: note: in implicit destructor for 'OpenDDS::XTypes::External<OpenDDS::XTypes::TypeIdentifier>' first required here
  409 |     PlainSequenceSElemDefn()
      |     ^
/home/runner/work/OpenDDS/OpenDDS/OpenDDS/dds/DCPS/XTypes/TypeObject.h:341:9: note: forward declaration of 'OpenDDS::XTypes::TypeIdentifier'
  341 |   class TypeIdentifier;
      |         ^
make[1]: Entering directory '/home/runner/work/OpenDDS/OpenDDS/OpenDDS/tests/DCPS/TcpReconnect'
touch .depend.stub
1 error generated.
```

### PR DESCRIPTION
**Pull request by mitza-oci**
resolves #5076, resolves #5091

### CODE REVIEW

File: dds/idl/langmap_generator.cpp [hunk 1]
```diff
@@ -1524,12 +1524,19 @@ struct Cxx11Generator : GeneratorBase {
...
-      be_global->add_include("<utility>", BE_GlobalData::STREAM_LANG_H);
+      be_global->add_include("<utility>", BE_GlobalData::STREAM_CPP);
       be_global->lang_header_ <<
-        "  void " << af.name_ << "(const " << lang_field_type << "& val) " << assign <<
-        "  void " << af.name_ << '(' << lang_field_type << "&& val) " << move <<
+        "  void " << af.name_ << "(const " << lang_field_type << "& val);\n"
+        "  void " << af.name_ << '(' << lang_field_type << "&& val);\n"
         "  const " << lang_field_type << "& " << af.name_ << "() const " << ret <<
         "  " << lang_field_type << "& " << af.name_ << "() " << ret;
+      AST_Decl* const scope = dynamic_cast<AST_Decl*>(field->defined_in());
```
Comment (jwillemsen) [inline dds/idl/langmap_generator.cpp:1533]: The implementation only has to be done out of the class declaration when the field is a sequence of a forward declared type, not in all cases, doing it always does increase the SLOC count for structs a lot

Comment (mitza-oci) [reply dds/idl/langmap_generator.cpp:1533]: It's the same line of code, just moved from `.h` to `.cpp`.

I think it would be complex to find all such cases (including maps and IDL4/XTypes `@external`), but if someone wanted to implement it that would be great.
